import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";

const MapNoSSR = dynamic(() => import("../components/MapNoSSR"), {
  ssr: false,
});

const Map: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Map</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <MapNoSSR />
      </main>
    </div>
  );
};

export default Map;
